var searchData=
[
  ['ramdisk_2ec_0',['ramdisk.c',['../ramdisk_8c.html',1,'']]],
  ['ramdisk_2eh_1',['ramdisk.h',['../ramdisk_8h.html',1,'(Global Namespace)'],['../RamDisk_8h.html',1,'(Global Namespace)']]],
  ['readonlyvariable2_2eh_2',['ReadOnlyVariable2.h',['../ReadOnlyVariable2_8h.html',1,'']]],
  ['realtimeclock_2eh_3',['RealTimeClock.h',['../RealTimeClock_8h.html',1,'']]],
  ['recoverymodule_2eh_4',['RecoveryModule.h',['../RecoveryModule_8h.html',1,'']]],
  ['rect_2ecpp_5',['rect.cpp',['../DeodhaiXR_2rect_8cpp.html',1,'(Global Namespace)'],['../Deodhai_2rect_8cpp.html',1,'(Global Namespace)']]],
  ['rect_2eh_6',['rect.h',['../DeodhaiXR_2rect_8h.html',1,'(Global Namespace)'],['../Deodhai_2rect_8h.html',1,'(Global Namespace)']]],
  ['regularexpressionprotocol_2eh_7',['RegularExpressionProtocol.h',['../RegularExpressionProtocol_8h.html',1,'']]],
  ['reportstatuscodehandler_2eh_8',['reportstatuscodehandler.h',['../Protocol_2ReportStatusCodeHandler_8h.html',1,'(Global Namespace)'],['../Ppi_2ReportStatusCodeHandler_8h.html',1,'(Global Namespace)']]],
  ['reportstatuscodelib_2eh_9',['ReportStatusCodeLib.h',['../ReportStatusCodeLib_8h.html',1,'']]],
  ['res_2ec_10',['res.c',['../res_8c.html',1,'']]],
  ['res_2eh_11',['res.h',['../res_8h.html',1,'']]],
  ['reset_2eh_12',['reset.h',['../Ppi_2Reset_8h.html',1,'(Global Namespace)'],['../Protocol_2Reset_8h.html',1,'(Global Namespace)']]],
  ['reset2_2eh_13',['Reset2.h',['../Reset2_8h.html',1,'']]],
  ['resetnotification_2eh_14',['ResetNotification.h',['../ResetNotification_8h.html',1,'']]],
  ['resourcepublicationlib_2eh_15',['ResourcePublicationLib.h',['../ResourcePublicationLib_8h.html',1,'']]],
  ['rest_2eh_16',['Rest.h',['../Rest_8h.html',1,'']]],
  ['rng_2eh_17',['Rng.h',['../Rng_8h.html',1,'']]],
  ['rnglib_2eh_18',['RngLib.h',['../RngLib_8h.html',1,'']]],
  ['roundf_2ecpp_19',['roundf.cpp',['../roundf_8cpp.html',1,'']]],
  ['route_2ec_20',['route.c',['../route_8c.html',1,'']]],
  ['route_2ecpp_21',['route.cpp',['../route_8cpp.html',1,'']]],
  ['route_2eh_22',['route.h',['../route_8h.html',1,'']]],
  ['rpi3_2eh_23',['rpi3.h',['../rpi3_8h.html',1,'']]],
  ['rpi3bp_2ec_24',['rpi3bp.c',['../rpi3bp_8c.html',1,'']]],
  ['rpi3bp_2eh_25',['rpi3bp.h',['../rpi3bp_8h.html',1,'']]],
  ['rpi3bp_5fgpio_2eh_26',['rpi3bp_gpio.h',['../rpi3bp__gpio_8h.html',1,'']]],
  ['rpi3bp_5fspi_2eh_27',['rpi3bp_spi.h',['../rpi3bp__spi_8h.html',1,'']]],
  ['rpi3bpgpio_2ec_28',['rpi3bpGPIO.c',['../rpi3bpGPIO_8c.html',1,'']]],
  ['rpi3bpirq_2ec_29',['rpi3bpIRQ.c',['../rpi3bpIRQ_8c.html',1,'']]],
  ['rpi3bpspi_2ec_30',['rpi3bpSPI.c',['../rpi3bpSPI_8c.html',1,'']]],
  ['rpi_5fili9486_2ec_31',['rpi_ili9486.c',['../rpi__ili9486_8c.html',1,'']]],
  ['rpi_5fili9486_2eh_32',['rpi_ili9486.h',['../rpi__ili9486_8h.html',1,'']]],
  ['rrect_2ecpp_33',['rrect.cpp',['../rrect_8cpp.html',1,'']]],
  ['rsaddr_2ec_34',['rsaddr.c',['../rsaddr_8c.html',1,'']]],
  ['rscalc_2ec_35',['rscalc.c',['../rscalc_8c.html',1,'']]],
  ['rscreate_2ec_36',['rscreate.c',['../rscreate_8c.html',1,'']]],
  ['rsdump_2ec_37',['rsdump.c',['../rsdump_8c.html',1,'']]],
  ['rsdumpinfo_2ec_38',['rsdumpinfo.c',['../rsdumpinfo_8c.html',1,'']]],
  ['rsinfo_2ec_39',['rsinfo.c',['../rsinfo_8c.html',1,'']]],
  ['rsio_2ec_40',['rsio.c',['../rsio_8c.html',1,'']]],
  ['rsirq_2ec_41',['rsirq.c',['../rsirq_8c.html',1,'']]],
  ['rslist_2ec_42',['rslist.c',['../rslist_8c.html',1,'']]],
  ['rsmemory_2ec_43',['rsmemory.c',['../rsmemory_8c.html',1,'']]],
  ['rsmisc_2ec_44',['rsmisc.c',['../rsmisc_8c.html',1,'']]],
  ['rsserial_2ec_45',['rsserial.c',['../rsserial_8c.html',1,'']]],
  ['rsutils_2ec_46',['rsutils.c',['../rsutils_8c.html',1,'']]],
  ['rsxface_2ec_47',['rsxface.c',['../rsxface_8c.html',1,'']]],
  ['rtc_2ecpp_48',['rtc.cpp',['../rtc_8cpp.html',1,'']]],
  ['rtc_2eh_49',['rtc.h',['../rtc_8h.html',1,'']]],
  ['rtcmmio_2ec_50',['rtcmmio.c',['../rtcmmio_8c.html',1,'']]],
  ['rtcmmio_2eh_51',['rtcmmio.h',['../rtcmmio_8h.html',1,'']]],
  ['runtime_2eh_52',['Runtime.h',['../Runtime_8h.html',1,'']]]
];
